#!/usr/bin/env python3
"""
Post the English translation of a Zenn article to dev.to via API.
Reads from substack/<slug>-eng.md (generated by translate_and_draft.py).
Usage: python scripts/post_devto.py articles/<slug>.md

Requires: DEV_TO_API_KEY, ZENN_USERNAME environment variables
State:    devto/state.json  (tracks article_id per slug)
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
import yaml
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DEVTO_DIR = REPO_ROOT / "devto"
STATE_FILE = DEVTO_DIR / "state.json"
DEVTO_API = "https://dev.to/api"


def parse_frontmatter(content: str) -> tuple[dict, str]:
    if not content.startswith("---"):
        return {}, content
    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}, content
    meta = yaml.safe_load(parts[1]) or {}
    return meta, parts[2].strip()


def parse_eng_file(content: str) -> tuple[str, str]:
    """Parse substack eng file → (title, body_without_title)."""
    _, body = parse_frontmatter(content)
    lines = body.splitlines()
    title = ""
    body_lines = []
    for i, line in enumerate(lines):
        if line.startswith("# ") and not title:
            title = line[2:].strip()
        else:
            body_lines.append(line)
    return title, "\n".join(body_lines).strip()


def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def save_state(state: dict):
    DEVTO_DIR.mkdir(exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n")


def devto_request(method: str, path: str, data: dict, api_key: str) -> dict:
    url = f"{DEVTO_API}{path}"
    payload = json.dumps(data).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "api-key": api_key,
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0",
        },
        method=method,
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"dev.to API error {e.code}: {body}")
        raise


def post_to_devto(slug: str, zenn_meta: dict, eng_path: Path, api_key: str, zenn_username: str, state: dict):
    content = eng_path.read_text()
    title, body = parse_eng_file(content)
    if not title:
        print(f"Error: could not parse title from {eng_path}")
        sys.exit(1)

    # dev.to tags: max 4, lowercase, alphanumeric + underscores only
    raw_tags = zenn_meta.get("topics") or []
    tags = [re.sub(r"[^a-z0-9]", "", t.lower()) for t in raw_tags[:4]]
    tags = [t for t in tags if t]

    canonical_url = f"https://zenn.dev/{zenn_username}/articles/{slug}"

    payload = {
        "article": {
            "title": title,
            "body_markdown": body,
            "published": True,
            "tags": tags,
            "canonical_url": canonical_url,
        }
    }

    article_id = state.get(slug, {}).get("article_id")
    if article_id:
        devto_request("PUT", f"/articles/{article_id}", payload, api_key)
        url = state[slug]["url"]
        print(f"Updated: {url}")
    else:
        result = devto_request("POST", "/articles", payload, api_key)
        article_id = result["id"]
        url = result["url"]
        state[slug] = {"article_id": article_id, "url": url}
        save_state(state)
        print(f"Posted: {url}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/post_devto.py articles/<slug>.md")
        sys.exit(1)

    api_key = os.environ.get("DEV_TO_API_KEY")
    if not api_key:
        print("Error: DEV_TO_API_KEY is not set")
        sys.exit(1)

    zenn_username = os.environ.get("ZENN_USERNAME")
    if not zenn_username:
        print("Error: ZENN_USERNAME is not set")
        sys.exit(1)

    article_path = Path(sys.argv[1])
    if not article_path.exists():
        print(f"Error: {sys.argv[1]} not found")
        sys.exit(1)

    slug = article_path.stem
    eng_path = REPO_ROOT / "substack" / f"{slug}-eng.md"
    if not eng_path.exists():
        print(f"Error: English version not found: {eng_path}")
        print("Run 'bash scripts/post.sh articles/<slug>.md' first to generate it.")
        sys.exit(1)

    content = article_path.read_text()
    meta, _ = parse_frontmatter(content)

    if not meta.get("published", False):
        print(f"Skip {article_path.name}: published=false")
        sys.exit(0)

    state = load_state()
    post_to_devto(slug, meta, eng_path, api_key, zenn_username, state)


if __name__ == "__main__":
    main()
